# Generated by Django 4.2.20 on 2025-03-31 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geotune', '0003_playlistkommentar_delete_kommentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('erstellungsdatum', models.DateTimeField(default=django.utils.timezone.now)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='geotune.playlist')),
            ],
            options={
                'ordering': ['-erstellungsdatum'],
            },
        ),
        migrations.DeleteModel(
            name='PlaylistKommentar',
        ),
    ]
