# Generated by Django 4.2.20 on 2025-04-03 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geotune', '0006_gamification_referenz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geocache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('schwierigkeit', models.IntegerField(choices=[(1, 'Sehr einfach'), (2, 'Einfach'), (3, 'Mittel'), (4, 'Schwer'), (5, 'Sehr schwer')], default=3)),
                ('belohnung', models.CharField(blank=True, max_length=255)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erstellte_geocaches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lied',
            name='plattform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lied',
            name='streaming_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamification',
            name='aktivitaet',
            field=models.CharField(choices=[('anmeldung', 'Tägliche Anmeldung'), ('playlist_erstellen', 'Playlist erstellen'), ('kommentar', 'Kommentar schreiben'), ('freund_einladen', 'Freund einladen'), ('event_teilnahme', 'Event-Teilnahme'), ('geocache_fund', 'Geocache gefunden')], max_length=50),
        ),
        migrations.CreateModel(
            name='GeocacheFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funddatum', models.DateTimeField(default=django.utils.timezone.now)),
                ('bewertung', models.IntegerField(blank=True, null=True)),
                ('kommentar', models.TextField(blank=True)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geotune.geocache')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Geocache Funde',
                'unique_together': {('nutzer', 'geocache')},
            },
        ),
        migrations.AddField(
            model_name='geocache',
            name='finder',
            field=models.ManyToManyField(related_name='gefundene_geocaches', through='geotune.GeocacheFund', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geocache',
            name='koordinaten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocaches', to='geotune.standort'),
        ),
    ]
